[tool.poetry]
name = "cleanrl"
version = "1.0.0"
description = "High-quality single file implementation of Deep Reinforcement Learning algorithms with research-friendly features"
authors = ["Costa Huang <costa.huang@outlook.com>"]
include = ["cleanrl_utils"]
keywords = ["reinforcement", "machine", "learning", "research"]
license="MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
tensorboard = "^2.10.0"
wandb = "^0.13.6"
gym = "0.23.1"
torch = ">=1.13.1"
stable-baselines3 = "1.2.0"
gymnasium = "^0.26.3"
moviepy = "^1.0.3"
pygame = "2.1.0"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.20.0"

[tool.poetry.group.atari]
optional = true
[tool.poetry.group.atari.dependencies]
ale-py = "0.7.4"
AutoROM = {extras = ["accept-rom-license"], version = "^0.4.2"}
opencv-python = "^4.6.0.66"

[tool.poetry.group.pytest]
optional = true
[tool.poetry.group.pytest.dependencies]
pytest = "^7.1.3"

[tool.poetry.group.optuna]
optional = true
[tool.poetry.group.optuna.dependencies]
optuna = "^3.0.1"
optuna-dashboard = "^0.7.2"
rich = "<12.0"

[tool.poetry.group.envpool]
optional = true
[tool.poetry.group.envpool.dependencies]
envpool = "^0.6.4"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
